apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestd-dp2-prep-config
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.configMaps.argoSyncWave }}"
data:
  ingestD.yaml: |
    brokers:
      - my-cluster-kafka-bootstrap:9092
    group_id: "ral_ingestd"
    num_messages: 50
    butler_repo: dp2_prep
    topics:
      RAL_BUTLER_DISK-dp2_prep:
        rucio_prefix: davs://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/butler/repos/dp2_prep/