apiVersion: v1
kind: ConfigMap
metadata:
  name: grid-certs
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.configMaps.argoSyncWave }}"
data:
{{ (.Files.Glob "files/grid-security/certificates/*").AsConfig | indent 2 }}