apiVersion: v1
kind: ServiceAccount
metadata:
  name: lsst-voms-proxy-writer
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.vomsRenewal.proxyWriterAccount.argoSyncWave }}
