# Role for granting permissions for writing secrets in the LSST namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lsst-secret-writer-role
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.vomsRenewal.proxyWriterRole.argoSyncWave }}"
rules:
{{ .Values.vomsRenewal.proxyWriterRole.rules | toYaml | indent 2 }}