apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: lsst-secret-writer-role-binding
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.vomsRenewal.proxyWriterBinding.argoSyncWave }}
subjects:
{{ .Values.vomsRenewal.proxyWriterBinding.subjects | toYaml | indent 2 }}
roleRef:
  kind: {{ .Values.vomsRenewal.proxyWriterBinding.roleRef.kind }}
  name: {{ .Values.vomsRenewal.proxyWriterBinding.roleRef.name }}
  apiGroup: {{ .Values.vomsRenewal.proxyWriterBinding.roleRef.apiGroup }}