# CronJob resource for renewing VOMS proxy credentials on a scheduled basis, 
# and a Job resource for performing the renewal upon installation.
apiVersion: batch/v1
kind: CronJob
metadata:
  name: lsst-renew-voms-proxy
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.vomsRenewal.cron.argoSyncWave }}"
spec:
  schedule: {{ .Values.vomsRenewal.cron.schedule }}
  successfulJobsHistoryLimit: {{ .Values.vomsRenewal.cron.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.vomsRenewal.cron.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ .Values.vomsRenewal.cron.ttlSecondsAfterFinished }}
      backoffLimit: {{ .Values.vomsRenewal.cron.backoffLimit | default 1 }}
      template:
        spec:
          serviceAccountName: {{ .Values.vomsRenewal.cron.serviceAccountName }}
          imagePullSecrets:
            - name: {{ .Values.vomsRenewal.image.imagePullSecrets }}
          restartPolicy: {{ .Values.vomsRenewal.cron.restartPolicy }}
          containers:
            - name: renew-voms-cron
              image: {{ .Values.vomsRenewal.image.repository }}:{{ .Values.vomsRenewal.image.tag }}
              imagePullPolicy: {{ .Values.vomsRenewal.image.pullPolicy }}
              volumeMounts:
{{ .Values.vomsRenewal.secretMounts | toYaml | indent 16 }}
          volumes:
{{ .Values.vomsRenewal.volumes | toYaml | indent 12 }}

---

apiVersion: batch/v1
kind: Job
metadata:
  name: lsst-renew-voms-proxy-on-install   
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.vomsRenewal.installJob.argoSyncWave }}"

spec:
  template:
    spec:
      serviceAccountName: {{ .Values.vomsRenewal.installJob.serviceAccountName }}
      restartPolicy: {{ .Values.vomsRenewal.installJob.restartPolicy }}
      imagePullSecrets:
        - name: {{ .Values.vomsRenewal.image.imagePullSecrets }}
      containers:
        - name: renew-voms-init
          image: {{ .Values.vomsRenewal.image.repository }}:{{ .Values.vomsRenewal.image.tag }}
          imagePullPolicy: {{ .Values.vomsRenewal.image.pullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              echo "Starting debug mode..."
              sleep infinity
          volumeMounts:
{{ .Values.vomsRenewal.secretMounts | toYaml | indent 16 }}
      volumes:
{{ .Values.vomsRenewal.volumes | toYaml | indent 12 }}
