apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-pods
  namespace: lsst-drp-kafka
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      strimzi.io/name: my-cluster-kafka
  endpoints:
  - port: tcp-prometheus
    path: /metrics
