apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.kafka.storage.className }}
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: {{ .Values.kafka.storage.reclaimPolicy }}
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: {{ .Values.kafka.storage.numberOfReplicas | quote }}
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "xfs"
  dataLocality: "disabled"
  unmapMarkSnapChainRemoved: "ignored"
  disableRevisionCounter: "true"
  dataEngine: "v1"