apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-cluster-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/cmwinterburn-stfc/lsst-drp-kafka.git'
    targetRevision: HEAD 
    path: messaging-stack/strimzi-cluster-operator
    helm:
      releaseName: strimzi-cluster-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lsst-drp-kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true