apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi
  namespace: flux-system
spec:
  interval: 10m
  targetNamespace: lsst-drp-kafka
  chart:
    spec:
      chart: ./my-strimzi-chart
      sourceRef:
        kind: GitRepository
        name: strimzi
        namespace: flux-system
      interval: 10m
  values:
    replicaCount: 2