apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: strimzi-cluster-operator
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: lsst-drp-kafka
  chart:
    spec:
      chart: strimzi-kafka-operator
      version: 0.49.1
      sourceRef:
        kind: HelmRepository
        name: strimzi-cluster-operator-source
        namespace: flux-system

