apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: promtail
  namespace: argocd
spec:
  project: default
  sources:
    # Official Grafana Helm charts repo
    - repoURL: https://grafana.github.io/helm-charts
      chart: promtail
      targetRevision: 6.17.1
      helm:
        releaseName: promtail
        valueFiles:
          - $values/messaging-stack/logging/promtail/values.yaml

    - repoURL: 'https://github.com/cmwinterburn-stfc/lsst-drp-kafka.git'
      targetRevision: main
      ref: values
      
  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true