# PodMonitor resource to monitor Kafka Bridge pods using Prometheus. 
# This configuration allows Prometheus to scrape metrics from the Kafka Bridge application.
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-bridge-pods
  namespace: lsst-drp-kafka
  labels:
    release: rancher-monitoring
spec:
  selector:
    matchLabels:
      strimzi.io/name: my-bridge-bridge
  podMetricsEndpoints:
  - port: rest-api
    path: /metrics
    interval: 10s
