# PodMonitor resource to monitor Kafka Broker pods using Prometheus. 
# This configuration allows Prometheus to scrape metrics from the Kafka Broker application.
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kafka-pods
  namespace: lsst-drp-kafka
  labels:
    release: rancher-monitoring
spec:
  selector:
    matchLabels:
      strimzi.io/name: my-cluster-kafka
  podMetricsEndpoints:
  - port: tcp-prometheus
    path: /metrics
    interval: 10s
