apiVersion: v1
kind: ConfigMap
metadata:
  name: butler-repos-index
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.configMaps.argoSyncWave }}"
data:
  butler-repos-index.yaml: |
    panda-test-med-1:  /etc/butler.yaml
    hsc_pdr2_multisite: /etc/butler.yaml
    dc2: /etc/butler.yaml
    ccms1: /etc/butler.yaml
    dp2_prep: /etc/butler.yaml
