project: default
source:
  repoURL: 'https://strimzi.io/charts/'
  targetRevision: 0.49.1
  helm:
    releaseName: strimzi-cluster-operator
  chart: strimzi-kafka-operator
destination:
  server: 'https://kubernetes.default.svc'
  namespace: lsst-drp-kafka
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true