project: default
source:
  repoURL: 'https://github.com/cmwinterburn-stfc/lsst-drp-kafka.git'
  path: messaging-stack/my-strimzi-chart
  targetRevision: main
  helm:
    releaseName: strimzi
destination:
  server: 'https://kubernetes.default.svc'
  namespace: lsst-drp-kafka
syncPolicy:
  automated:
    prune: true
    selfHeal: true