apiVersion: v1
kind: ConfigMap
metadata:
  name: ingestd-ccms-config
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.configMaps.argoSyncWave }}
data:
  ingestD.yaml: |
    brokers:
      - my-cluster-kafka-bootstrap:9092
    group_id: "ral_ingestd"
    num_messages: 50
    butler_repo: ccms1
    topics:
      RAL_BUTLER_DISK-ccms1:
        rucio_prefix: davs://webdav.echo.stfc.ac.uk:1094/lsst:datadisk/butler/repos/ccms1/