apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingestd-poller
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.ingestd.serviceAccount.argoSyncWave }}"
