apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.ingestd.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .Values.ingestd.argoSyncWave }}"

spec:
  replicas: {{ .Values.ingestd.spec.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.ingestd.spec.selector.matchLabels.app }}

  template:
    metadata:
      labels:
        app: {{ .Values.ingestd.spec.template.metadata.labels.app }}

    spec:
    #Initialise the init container to prepare the Butler DB auth file with correct permissions before the main container starts
      initContainers:
        - name: {{ .Values.ingestd.initContainer.name }}
          image: {{ .Values.ingestd.initContainer.image }}  
          command:
            - sh
            - -c
            - |
              echo "Preparing Butler DB auth file..."
              cp /secret-src/db-auth.yaml /work/db-auth.yaml
              chown 1000:1000 /work/db-auth.yaml
              chmod 600 /work/db-auth.yaml
              ls -l /work/db-auth.yaml
              echo "Done."

              echo "Preparing X.509 proxy..."
              cp /proxy-src/x509up_u99 /work/x509up
              chown 1000:1000 /work/x509up
              chmod 400 /work/x509up
              ls -l /work/x509up
              echo "Done."

          volumeMounts: 
{{ .Values.ingestd.initContainer.volumeMounts | toYaml | indent 12 }}

      containers:
        - name: {{ .Values.ingestd.container.name }}
          image: {{ .Values.ingestd.container.image }}
          imagePullPolicy: {{ .Values.ingestd.container.imagePullPolicy }}
          securityContext:
            runAsUser: {{ .Values.ingestd.container.securityContext.runAsUser }}
            runAsGroup: {{ .Values.ingestd.container.securityContext.runAsGroup }}
          env:
{{ toYaml .Values.ingestd.container.env | indent 12 }}
          volumeMounts:
{{toYaml .Values.ingestd.container.volumeMounts | indent 12 }}

      volumes:
{{- range $name, $vol := .Values.ingestd.volumes }}
        - name: {{ $name }}
{{ toYaml $vol | nindent 10 }}
{{- end }}
