apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: lsst-secret-writer-role
  namespace: lsst-drp-kafka
  annotations:
    argocd.argoproj.io/sync-wave: "0"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]