vomsRenewal:
  enabled: 0

  schedule: "42 */6 * * *"

  image:
    repository: "harbor.stfc.ac.uk/ral-tier1_public/lsst/voms-proxy-renewal"
    tag: test-2025-02-18
    pullPolicy: Always

  volumes:
    - name: lsst-voms-config
      configMap:
        name: lsst-voms-config
    - name: voms-long-proxy
      secret:
        secretName: long-proxy

  secretMounts:
    - name: voms-long-proxy
      mountPath: /etc/certs/

  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
